#!/usr/bin/env python

GROVEPI_CHANNEL_THROTTLE_L = 6
GROVEPI_CHANNEL_THROTTLE_R = 5
GROVEPI_CHANNEL_DIRECTION_L = 7
GROVEPI_CHANNEL_DIRECTION_R = 8
GROVEPI_CHANNEL_THROTTLE_TURRET = 3
GROVEPI_CHANNEL_DIRECTION_TURRET_1 = 2
GROVEPI_CHANNEL_DIRECTION_TURRET_2 = 4
GROVEPI_CHANNEL_GUN = 16
GROVEPI_CHANNEL_BUZZER = 15

GROVEPI_PWM_MIN = 16.0
GROVEPI_PWM_MAX = 255.0

_debug = False
